targets:
  $default:
    sources:
      # --
      # Note that it is important to include these in the default target.
      - pubspec.*
      - $package$
      - lib/$lib$
      # --
      - widgetbook/lib/main.dart
      - lib/**
      - main_app/lib/**
    builders:
      widgetbook_generator:use_case_builder:
        generate_for:
          - lib/**
          - main_app/lib/**
